# volume up <user.n20>: key("volup:{n20}")
# volume down <user.n20>: key("voldown:{n20}")
# music next <user.n20>: key("next:{n20}")
# music previous <user.n20>: key("prev:{n20}")
# music play: key(play)
volume up <user.n20>: user.music_volup(n20)
volume down <user.n20>: user.music_voldown(n20)
music next <user.n20>: user.music_next(n20)
music previous <user.n20>: user.music_prev(n20)
music play: user.music_play()