volume up [<user.n20>]: key("volup:{n20 or 1}")
volume down [<user.n20>]: key("voldown:{n20 or 1}")
music next [<user.n20>]: key("next:{n20 or 1}")
music previous [<user.n20>]: key("prev:{n20 or 1}")
music play: key(play)