volume up [<user.n20>]: key("volup:{n20 or 1}")
volume down [<user.n20>]: key("voldown:{n20 or 1}")
volume low: key(voldown:50 volup:1)
volume (mid | medium): key(voldown:50 volup:10)
volume high: key(voldown:50 volup:25)
music next [<user.n20>]: key("next:{n20 or 1}")
music previous [<user.n20>]: key("prev:{n20 or 1}")
music play: key(play)
