# Once you have finished making changes, use the "rebuild caster"
# command to enact them.
"numbers_max"          = 500
"pronunciation"        = "Core"
"capitals_prefix"      = "big"
"numbers_prefix"       = "numb"
"dictation_prefix"     = "(say)"
"extreme"              = "wally"

[search]
"amazon"   = "https://smile.amazon.co.uk/s?k=%s"
"google"   = "https://www.google.com/search?q=%s"
"kindle"   = "https://smile.amazon.co.uk/s?k=%s&rh=n%%3A341689031"
"morrisons"= "https://groceries.morrisons.com/search?entry=%s"
"python"   = "https://www.google.com/search?q=python+%s"
"wikipedia"= "https://en.wikipedia.org/w/index.php?search=%s"
"youtube"  = "https://www.youtube.com/results?search_query=%s"

[letters_alt]
"anti"                 = "a"
"bat"                  = "b"
"cap"                  = "c"
"die"                  = "d"
"each"                 = "e"
"fail"                 = "f"
"gone"                 = "g"
"harp"                 = "h"
"sit"                  = "i"
"jury"                 = "j"
"crunch"               = "k"
"look"                 = "l"
"made"                 = "m"
"near"                 = "n"
"odd"                  = "o"
"pet"                  = "p"
"queer"                = "q"
"red"                  = "r"
"sun"                  = "s"
"trap"                 = "t"
"urge"                 = "u"
"vest"                 = "v"
"whale"                = "w"
"box"                  = "x"
"yes"                  = "y"
"zulu"                 = "z"

[punctuation]
"apostrophe"              = "'"
"backslash"               = "\\"
"backtick"                = "`"
"caret"                   = "^"
"comma"                   = ","
"co lace"                 = ": space"
"boom"         = ", space"
"boomer"         = ", space"
"dollar"                  = "$"
"point"                   = "."
"thin quotes"             = "'"
"quote"        = '"'
"quotes"        = '"'
"hashtag"                 = "#"
"hyphen"                  = "-"
"semicolon"               = ";"
"tilde"                   = "~"
"underscore"              = "_"
"greater than"            = ">"
"greater equal"           = "> ="
"less than"               = "<"
"less equal"              = "< ="
"equal to"                = "space = = space"
"angle"                   = "< > left"
"prekris"       = "( ) left"
"prens"       = "( ) left"
"brax"                    = "[ ] left"
"curly"                   = "{ } left"
"left paren"              = "("
"right paren"   = ")"
"left bracket"            = "["
"right bracket" = "]"
"left brace"              = "{"
"right brace"   = "}"

[punctuation2]
"equals"                  = "="
"ampersand"               = "&"
"starling"              = "*"
"at sign"                 = "@"
"pipe symbol"             = "|"
"colon"                   = ":"
"clamor"                  = "!"
"minus"                   = "-"
"modulo"                  = "%"
"plus"                    = "+"
"questo"                  = "?"
"slash"                   = "/"

[keys]
"ace"        = "space"
"space"        = "space"
"tabby"              = "tab"
"tabby lease"         = "shift-tab"
"shock"                = "enter"
# "check"                = "ctrl-enter"
"clear"   = "backspace"
"clearing"   = "backspace"
"splat"              = "ctrl-backspace"
"splat ross"        = "ctrl-delete"
"deli"                 = "delete"
"page up"              = "pgup"
"page down"            = "pgdown"
# "undo"          = "ctrl-z"
"redo"          = "ctrl-y"
"zoom in" = "ctrl-="
"zoom out" = "ctrl--"
# "duple" = "home shift-end ctrl-c ctrl-enter ctrl-v"


[misc_core_keys]
# "stoosh" = "ctrl-c"
# "spark" = "ctrl-v"
"cutter" = "ctrl-x"
"eskimo"               = "escape"
"ski"               = "escape"
"shackle"              = "home shift-end"
"select all"           = "ctrl-a"
"find"                 = "ctrl-f"


# [misc_core_keys_noCCR]

[directions]
"lease"                = "left"
"ross"                 = "right"
"sauce"                = "up"
"dunce"                = "down"

[modifiers]
"queue"                = "ctrl-shift-"
"shin"                 = "shift-"
"fly"                  = "ctrl-"

[enclosures]
"prekris"              = "(~)"
"angle"                = "<~>"
"curly"                = "{~}"
"brax"                 = "[~]"
"thin quotes"          = "'~'"
'quotes'               = '"~"'
'backticks'            = '`~`'

[capitalisation]
"yell"                 = "1"
"tie"                  = "2"
"(Gerrish | camel)"    = "3"
"sing"                 = "4"
"laws"                 = "5"
"password"             = "6"

[spacing]
"gum"                  = "1"
"gun"                  = "1"
"spine"                = "2"
"snake"                = "3"
"pebble"               = "4"
"incline"              = "5"
"dissent"              = "6"
"descent"              = "6"
"list"                 = "7"
"dictionary"           = "8"


[letters]
"alpha"                = "a"
"bravo"                = "b"
"charlie"              = "c"
"delta"                = "d"
"echo"                 = "e"
"foxtrot"              = "f"
"golf"                 = "g"
"hotel"                = "h"
"india"                = "i"
"juliet"               = "j"
"kilo"                 = "k"
"lima"                 = "l"
"mike"                 = "m"
"november"             = "n"
"oscar"                = "o"
"papa"                 = "p"
"quebec"               = "q"
"romeo"                = "r"
"sierra"               = "s"
"tango"                = "t"
"uniform"              = "u"
"victor"               = "v"
"whiskey"              = "w"
"x-ray"                = "x"
"yankee"               = "y"
"zulu"                 = "z"
